pipeline {
     agent any
     stages {
         stage('Build') {
            powershell ' .\\Scripts\\Build.ps1'
        }
        stage('Tests') {
            powershell ' .\\Scripts\\Tests.ps1'
        }
        stage('Publish') {
            powershell ' .\\Scripts\\Publish.ps1'
        }
     }
}
