pipeline {
     agent any
     stages {
         stage('Build') {
             steps {
                powershell ' .\\Scripts\\Build.ps1'
             }
        }
        stage('Tests') {
             steps {
                powershell ' .\\Scripts\\Tests.ps1'
             }
        }
        stage('Publish') {
             steps {
                powershell ' .\\Scripts\\Publish.ps1'
             }
        }
     }
}
